POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NDEyODA2YmJmYTU5ZjcwOWNiNWYyMzIiLCJpYXQiOjE2Nzk3NTExMTZ9.XXsQ55r6SYcQukauR8-xahqmwbuig4apiJytxpNcKT0

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12
}